spring.application.name=greenride-backend

spring.datasource.driver-class-name=org.postgresql.Driver
# The standard JDBC URL format for PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/greenride_db
# PostgreSQL database username
spring.datasource.username=postgres
# PostgreSQL database password
spring.datasource.password=160723@rd
# Specifies the dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update 

# Show SQL statements in the console (useful for debugging)
spring.jpa.show-sql=true
# Format the SQL to be more readable
spring.jpa.properties.hibernate.format_sql=true

# The port where your application will run (default is 8080)
server.port=8080

#for logs to debug the application
logging.level.org.springframework.security=DEBUG
# JWT Configuration
#greenride.app.jwtSecret=YOURULTRASFCSECURESECRETKEYGOESHEREATLEAST32CHARS1234567890
# ENSURE THIS ENCODED STRING IS LONG ENOUGH TO DECODE TO >= 512 BITS
# Ensure this new key is AT LEAST 80 characters long before encoding
greenride.app.jwtSecret=AMUCHLONGERBASE64KEYATLEAST80CHARSLONGNOWGOESHERETOMEET512BITSREQ
greenride.app.jwtExpirationMs=86400000

# application.properties

# --- SMTP Configuration ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=deepakkhokhar0143@gmail.com  
spring.mail.password=qijhpaovzpgymaji    
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com